//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetExamenEntities : DbContext
    {
        public NetExamenEntities()
            : base("name=NetExamenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Demande> Demandes { get; set; }
        public virtual DbSet<Lycee> Lycees { get; set; }
        public virtual DbSet<Professeur> Professeurs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
